// Lookup helpers for the prebuilt (Chatterbox) audio committed under public/audio.
// The manifests are generated by `npm run tts:steps` / `npm run tts:passages`
// on a machine with the local GPU; days without a clip fall back to the
// on-demand Workers AI endpoint, so a missing entry is always safe.
import stepsManifest from './audioSteps.json';
import daysManifest from './audioDays.json';
import musicManifest from './singingBibleClips.json';
import type { Lang } from './reading';
import type { Step } from './dailySteps';

interface StepClip {
  file: string;
  hash: string;
  text: string;
}

const STEPS = stepsManifest as {
  generator: string;
  steps: Record<Lang, Partial<Record<Step, StepClip>>>;
};

const DAYS = daysManifest as {
  generator: string;
  days: Record<string, Lang[]>;
};

/** The prebuilt guidance clip for a step, or null when none was generated. */
export function stepAudioUrl(lang: Lang, step: Step): string | null {
  return STEPS.steps[lang]?.[step]?.file ?? null;
}

/** Whether this day's passage already has a prebuilt clip in this language. */
export function hasPrebuiltDayAudio(day: string, lang: Lang): boolean {
  return DAYS.days[day]?.includes(lang) ?? false;
}

/**
 * The static clip for a day's passage. Only meaningful when
 * hasPrebuiltDayAudio says so - the file otherwise 404s.
 */
export function prebuiltDayAudioUrl(lang: Lang, day: string): string {
  return `/audio/days/${lang}/${day}.mp3`;
}

/**
 * Every prebuilt clip key the endpoints may ever serve, derived from the
 * manifests: "steps/<lang>/<name>.mp3" and "days/<lang>/<day>.mp3" — the
 * site path minus the leading "audio/". Both the /audio/* route and /api/tts
 * gate on this set, so neither can be tricked into reading an arbitrary
 * object out of the AUDIO bucket.
 */
const R2_KEYS: ReadonlySet<string> = (() => {
  const keys = new Set<string>();
  for (const clips of Object.values(STEPS.steps)) {
    for (const clip of Object.values(clips)) {
      if (clip) keys.add(clip.file.replace(/^\/audio\//, ''));
    }
  }
  for (const [day, langs] of Object.entries(DAYS.days)) {
    for (const lang of langs) keys.add(`days/${lang}/${day}.mp3`);
  }
  return keys;
})();

/**
 * The R2 object key for a site audio URL like "/audio/steps/en/x.mp3", or
 * null when the URL is not a manifest-listed clip.
 */
export function audioR2Key(url: string): string | null {
  const key = url.replace(/^\/audio\//, '');
  return R2_KEYS.has(key) ? key : null;
}

/**
 * Pre-cut passage music keys, "music/singing-bible/<name>.mp3" - the site
 * path minus the leading "/". Like the TTS clips, the files are generated
 * locally, gitignored, and served from R2 so a git-triggered build (which
 * never has them) still ships working music.
 */
const MUSIC_R2_KEYS: ReadonlySet<string> = new Set(
  Object.values(musicManifest as Record<string, { file: string }>).map(clip => clip.file.slice(1)),
);

/** The R2 object key for a music URL like "/music/singing-bible/x.mp3", or null. */
export function musicR2Key(url: string): string | null {
  if (!url.startsWith('/music/')) return null;
  const key = url.slice(1);
  return MUSIC_R2_KEYS.has(key) ? key : null;
}
