// Lookup helpers for the prebuilt (Chatterbox) audio committed under public/audio.
// The manifests are generated by `npm run tts:steps` / `npm run tts:passages`
// on a machine with the local GPU; days without a clip fall back to the
// on-demand Workers AI endpoint, so a missing entry is always safe.
import stepsManifest from './audioSteps.json';
import daysManifest from './audioDays.json';
import type { Lang } from './reading';
import type { Step } from './dailySteps';

interface StepClip {
  file: string;
  hash: string;
  text: string;
}

const STEPS = stepsManifest as {
  generator: string;
  steps: Record<Lang, Partial<Record<Step, StepClip>>>;
};

const DAYS = daysManifest as {
  generator: string;
  days: Record<string, Lang[]>;
};

/** The prebuilt guidance clip for a step, or null when none was generated. */
export function stepAudioUrl(lang: Lang, step: Step): string | null {
  return STEPS.steps[lang]?.[step]?.file ?? null;
}

/** Whether this day's passage already has a prebuilt clip in this language. */
export function hasPrebuiltDayAudio(day: string, lang: Lang): boolean {
  return DAYS.days[day]?.includes(lang) ?? false;
}

/**
 * The static clip for a day's passage. Only meaningful when
 * hasPrebuiltDayAudio says so - the file otherwise 404s.
 */
export function prebuiltDayAudioUrl(lang: Lang, day: string): string {
  return `/audio/days/${lang}/${day}.mp3`;
}
