// Reader-facing access to the pre-written per-question interpretations.
//
// The verse library runs question -> verse in reverse: a visitor arrives on
// /library/<slug> from a question-shaped search, so each verse page carries
// its own reflection for each question in ./verseQuestions, plus an entry point
// for the reader's own question.
//
// Content lives in ./verseInterpretations.en.json and .zh.json, generated by
// scripts/generate-verse-interpretations.mts and validated by
// scripts/check-verse-interpretations.mjs. Both languages are bundled: the
// library is fully bilingual, so a ?lang=zh page must not open empty-handed.

import en from './verseInterpretations.en.json';
import zh from './verseInterpretations.zh.json';
import { TYPICAL_QUESTIONS, type TypicalQuestion } from './verseQuestions';
import { getLibraryVerseBySlug, type LibraryVerse } from './scripture';
import type { Lang } from './reading';

export interface VerseInterpretation {
  /** The reflection itself. */
  text: string;
  /** One short line worth carrying into the day. */
  carry: string;
}

/** One question paired with this verse's answer to it. */
export interface VerseQuestionEntry {
  question: TypicalQuestion;
  interpretation: VerseInterpretation;
}

const SOURCES: Record<Lang, Record<string, Record<string, VerseInterpretation>>> = {
  en: en as Record<string, Record<string, VerseInterpretation>>,
  zh: zh as Record<string, Record<string, VerseInterpretation>>,
};

/**
 * The questions this verse has a written interpretation for, in the canonical
 * question order. Empty when the verse has none (a gap in generation, or an
 * unknown slug) — callers then render the own-question entry point alone.
 */
export function interpretationsForVerse(slug: string, lang: Lang): VerseQuestionEntry[] {
  const byQuestion = SOURCES[lang][slug];
  if (!byQuestion) return [];
  return TYPICAL_QUESTIONS.flatMap((question) => {
    const interpretation = byQuestion[question.slug];
    if (!interpretation?.text) return [];
    return [{ question, interpretation }];
  });
}

/** True when a verse has at least one written interpretation in this language. */
export function hasInterpretations(slug: string, lang: Lang): boolean {
  return interpretationsForVerse(slug, lang).length > 0;
}

/**
 * Other verses that answer the same question, as library entries, for the
 * cross-links under each entry — the onward path for a visitor who came for
 * the question rather than the passage. Ordered as the deck is (the JSON keys
 * are written in deck order), minus the verse being viewed.
 *
 * Deterministic and evenly spaced through the list rather than the first N, so
 * the same handful of verses does not absorb every link on every page.
 */
export function versesForQuestion(
  questionSlug: string,
  lang: Lang,
  excludeSlug: string,
  max = 3
): LibraryVerse[] {
  const byQuestion = SOURCES[lang];
  const slugs = Object.keys(byQuestion).filter(
    (slug) => slug !== excludeSlug && Boolean(byQuestion[slug]?.[questionSlug]?.text)
  );
  if (slugs.length === 0) return [];
  const picked: string[] = [];
  const step = slugs.length / Math.min(max, slugs.length);
  for (let i = 0; i < Math.min(max, slugs.length); i++) {
    picked.push(slugs[Math.floor(i * step)]!);
  }
  return picked
    .map((slug) => getLibraryVerseBySlug(slug))
    .filter((v): v is LibraryVerse => v !== null);
}

/** How many verses answer a given question, for the entry-point labels. */
export function countForQuestion(questionSlug: string, lang: Lang): number {
  const byQuestion = SOURCES[lang];
  return Object.values(byQuestion).filter((entry) => Boolean(entry[questionSlug]?.text)).length;
}
